application: sanskritmetres
version: 1h
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /NotoSansDevanagariRegularUnhintedDownloaded\.ttf
  mime_type: font/ttf
  static_files: NotoSansDevanagariRegularUnhintedDownloaded.ttf
  upload: NotoSansDevanagariRegularUnhintedDownloaded\.ttf
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: .*
  script: request_handler.application

libraries:
- name: webapp2
  # version: "2.5.2"
  version: latest
